<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
	  <_Parameter1>Continuum.CSharpFunctionalExtensions.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Grpc.Net.Common" Version="2.83.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
  </ItemGroup>

</Project>
