<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Orleans.Runtime" Version="10.3.1" />
    <PackageReference Include="Microsoft.Orleans.Streaming" Version="10.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Surrogates\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Orleans\Continuum.Core.Orleans.csproj" />
    <ProjectReference Include="..\Streaming\Continuum.Streaming.csproj" />
  </ItemGroup>

</Project>
