<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<IsPackable>false</IsPackable>
	<RootNamespace>Continuum.Core.SourceGenerators.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="coverlet.collector" Version="10.1.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
	<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\..\src\Core\Continuum.Core.csproj" />
	<ProjectReference Include="..\..\src\Core.SourceGenerators\Continuum.Core.SourceGenerators.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Using Include="Xunit" />
  </ItemGroup>

</Project>
