using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Continuum.CSharpFunctionalExtensions.SourceGenerators;

/// <summary>
///     Implements <c>IEnumValueObjectMembers&lt;T&gt;</c> for every partial class deriving from
///     <c>EnumValueObject&lt;T&gt;</c> or <c>EnumValueObject&lt;T, TId&gt;</c>, listing its public static fields of type
///     <c>T</c> in declaration order. This replaces runtime reflection so enumerations work under trimming and Native AOT.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EnumValueObjectGenerator : IIncrementalGenerator
{
    private const string LibraryNamespace = "Continuum.CSharpFunctionalExtensions";
    private const string BaseTypeName = "EnumValueObject";
    private const string InterfaceName = "global::Continuum.CSharpFunctionalExtensions.IEnumValueObjectMembers";

    internal static readonly DiagnosticDescriptor MustBePartial = new(
        id: "CFE001",
        title: "EnumValueObject types must be partial",
        messageFormat: "'{0}' derives from EnumValueObject and must be declared partial (along with any containing types) so its members can be generated",
        category: "Continuum.CSharpFunctionalExtensions",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, ct) => GetModel((ClassDeclarationSyntax)ctx.Node, ctx.SemanticModel, ct))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(models, static (spc, model) =>
        {
            if (model.Error is { } error)
            {
                spc.ReportDiagnostic(Diagnostic.Create(MustBePartial, error.ToLocation(), model.DisplayName));
                return;
            }

            spc.AddSource(model.HintName!, SourceText.From(model.Source!, Encoding.UTF8));
        });
    }

    private static Model? GetModel(ClassDeclarationSyntax syntax, SemanticModel semanticModel, System.Threading.CancellationToken ct)
    {
        if (semanticModel.GetDeclaredSymbol(syntax, ct) is not INamedTypeSymbol type)
        {
            return null;
        }

        if (!IsEnumValueObject(type))
        {
            return null;
        }

        // A partial type may have several declarations; generate once, from the first.
        if (type.DeclaringSyntaxReferences.Length > 1 && type.DeclaringSyntaxReferences[0].GetSyntax(ct) != syntax)
        {
            return null;
        }

        var displayName = type.ToDisplayString(SymbolDisplayFormat.CSharpShortErrorMessageFormat);

        for (var t = type; t is not null; t = t.ContainingType)
        {
            var isPartial = t.DeclaringSyntaxReferences.Any(r =>
                r.GetSyntax(ct) is TypeDeclarationSyntax d && d.Modifiers.Any(SyntaxKind.PartialKeyword));
            if (!isPartial)
            {
                return new Model(displayName, null, null, LocationInfo.From(syntax.Identifier.GetLocation()));
            }
        }

        var members = type.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.IsStatic
                && f.DeclaredAccessibility == Accessibility.Public
                && SymbolEqualityComparer.Default.Equals(f.Type, type))
            .Select(f => f.Name)
            .ToImmutableArray();

        return new Model(displayName, GetHintName(type), BuildSource(type, members), null);
    }

    private static bool IsEnumValueObject(INamedTypeSymbol type)
    {
        for (var baseType = type.BaseType; baseType is not null; baseType = baseType.BaseType)
        {
            if (baseType.Name == BaseTypeName
                && baseType.ContainingNamespace.ToDisplayString() == LibraryNamespace
                && baseType.TypeArguments.Length is 1 or 2
                && SymbolEqualityComparer.Default.Equals(baseType.TypeArguments[0], type))
            {
                return true;
            }
        }

        return false;
    }

    private static string BuildSource(INamedTypeSymbol type, ImmutableArray<string> members)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            sb.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(";");
            sb.AppendLine();
        }

        var containers = new System.Collections.Generic.List<INamedTypeSymbol>();
        for (var t = type.ContainingType; t is not null; t = t.ContainingType)
        {
            containers.Insert(0, t);
        }

        var indent = "";
        foreach (var container in containers)
        {
            sb.Append(indent).Append("partial ").Append(Keyword(container)).Append(' ').AppendLine(NameWithTypeParameters(container));
            sb.Append(indent).AppendLine("{");
            indent += "    ";
        }

        var self = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.Append(indent).Append("partial class ").Append(NameWithTypeParameters(type))
            .Append(" : ").Append(InterfaceName).Append('<').Append(self).AppendLine(">");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    static ").Append(self).Append("[] ").Append(InterfaceName).Append('<').Append(self)
            .Append(">.GetMembers() => [").Append(string.Join(", ", members)).AppendLine("];");
        sb.Append(indent).AppendLine("}");

        for (var i = containers.Count - 1; i >= 0; i--)
        {
            indent = indent.Substring(4);
            sb.Append(indent).AppendLine("}");
        }

        return sb.ToString();
    }

    private static string Keyword(INamedTypeSymbol type) => type switch
    {
        { IsRecord: true, TypeKind: TypeKind.Struct } => "record struct",
        { IsRecord: true } => "record",
        { TypeKind: TypeKind.Struct } => "struct",
        { TypeKind: TypeKind.Interface } => "interface",
        _ => "class",
    };

    private static string NameWithTypeParameters(INamedTypeSymbol type) =>
        type.TypeParameters.Length == 0
            ? type.Name
            : type.Name + "<" + string.Join(", ", type.TypeParameters.Select(p => p.Name)) + ">";

    private static string GetHintName(INamedTypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "")
            .Replace('<', '[')
            .Replace('>', ']') + ".EnumValueObject.g.cs";

    private sealed record Model(string DisplayName, string? HintName, string? Source, LocationInfo? Error);

    private sealed record LocationInfo(string FilePath, TextSpan Span, LinePositionSpan LineSpan)
    {
        public static LocationInfo From(Location location) =>
            new(location.SourceTree?.FilePath ?? "", location.SourceSpan, location.GetLineSpan().Span);

        public Location ToLocation() => Location.Create(FilePath, Span, LineSpan);
    }
}
