using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Continuum.CSharpFunctionalExtensions.SourceGenerators;

/// <summary>
///     For every partial <c>JsonSerializerContext</c> that lists <c>Result</c> or <c>Result&lt;T&gt;</c> through
///     <c>[JsonSerializable]</c>, generates a static <c>AddResultConverters(JsonSerializerOptions)</c> method that registers
///     the matching Native AOT safe converters.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ResultJsonConvertersGenerator : IIncrementalGenerator
{
    private const string JsonSerializableAttribute = "System.Text.Json.Serialization.JsonSerializableAttribute";
    private const string LibraryNamespace = "Continuum.CSharpFunctionalExtensions";
    private const string ConverterNamespace = "global::Continuum.CSharpFunctionalExtensions.Json.Serialization";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
                JsonSerializableAttribute,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(models, static (spc, model) =>
            spc.AddSource(model.HintName, SourceText.From(model.Source, Encoding.UTF8)));
    }

    private static Model? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol context)
        {
            return null;
        }

        // A partial context may carry attributes on several declarations; generate once, from the first.
        if (context.DeclaringSyntaxReferences.Length > 1 && context.DeclaringSyntaxReferences[0].GetSyntax() != ctx.TargetNode)
        {
            return null;
        }

        var hasNonGeneric = false;
        var valueTypes = new List<string>();

        foreach (var attribute in context.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != JsonSerializableAttribute
                || attribute.ConstructorArguments.Length == 0
                || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol listed
                || listed.Name != "Result"
                || listed.ContainingNamespace.ToDisplayString() != LibraryNamespace)
            {
                continue;
            }

            if (listed.TypeArguments.Length == 0)
            {
                hasNonGeneric = true;
            }
            else if (listed.TypeArguments.Length == 1)
            {
                var valueType = listed.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (!valueTypes.Contains(valueType))
                {
                    valueTypes.Add(valueType);
                }
            }
        }

        if (!hasNonGeneric && valueTypes.Count == 0)
        {
            return null;
        }

        var hintName = context.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "").Replace('<', '_').Replace('>', '_') + ".ResultConverters.g.cs";

        return new Model(hintName, BuildSource(context, hasNonGeneric, valueTypes));
    }

    private static string BuildSource(INamedTypeSymbol context, bool hasNonGeneric, List<string> valueTypes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!context.ContainingNamespace.IsGlobalNamespace)
        {
            sb.Append("namespace ").Append(context.ContainingNamespace.ToDisplayString()).AppendLine(";");
            sb.AppendLine();
        }

        var containers = new List<INamedTypeSymbol>();
        for (var t = context.ContainingType; t is not null; t = t.ContainingType)
        {
            containers.Insert(0, t);
        }

        var indent = "";
        foreach (var container in containers)
        {
            sb.Append(indent).Append("partial ").Append(container.IsRecord ? "record" : container.TypeKind == TypeKind.Struct ? "struct" : "class")
                .Append(' ').AppendLine(container.Name);
            sb.Append(indent).AppendLine("{");
            indent += "    ";
        }

        sb.Append(indent).Append("partial class ").AppendLine(context.Name);
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    /// <summary>");
        sb.Append(indent).AppendLine("    ///     Registers the Native AOT safe Result converters for every Result type listed on this context.");
        sb.Append(indent).AppendLine("    /// </summary>");
        sb.Append(indent).AppendLine("    /// <param name=\"options\">The options to configure.</param>");
        sb.Append(indent).AppendLine("    /// <returns>The same <paramref name=\"options\"/> instance, for chaining.</returns>");
        sb.Append(indent).AppendLine("    public static global::System.Text.Json.JsonSerializerOptions AddResultConverters(global::System.Text.Json.JsonSerializerOptions options)");
        sb.Append(indent).AppendLine("    {");
        if (hasNonGeneric)
        {
            sb.Append(indent).Append("        options.Converters.Add(new ").Append(ConverterNamespace).AppendLine(".ResultJsonConverter());");
        }
        foreach (var valueType in valueTypes)
        {
            sb.Append(indent).Append("        options.Converters.Add(new ").Append(ConverterNamespace)
                .Append(".ResultJsonConverter<").Append(valueType).AppendLine(">());");
        }
        sb.Append(indent).AppendLine("        return options;");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");

        for (var i = containers.Count - 1; i >= 0; i--)
        {
            indent = indent.Substring(4);
            sb.Append(indent).AppendLine("}");
        }

        return sb.ToString();
    }

    private sealed record Model(string HintName, string Source);
}
