<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.63.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventSourcing.Orleans\Continuum.EventSourcing.Orleans.csproj" />
  </ItemGroup>

</Project>
